title: Project
pages: false
files:
  sortable: true
  max: null
  hide: false
  sanitize: true
  fields: null
  size: null
  width: null
  height: null
  fields:
    textSettings:
      label: Text Settings
      type: headline
    imageTitle:
      label: Title
      type: text
    imageFormat:
      label: Format
      type: text
      width: 1/2
    imageMaterials:
      label: Materials
      type: text
      width: 1/2
    imageText:
      label: Description
      help: Overrides the one by default
      type: textarea
    caption:
      label: Caption
      type: textarea
    gridSettings:
      label: Grid Settings
      type: headline
    notingrid:
      label: Remove from grid
      type: toggle
      default: no
      options:
        no: "no"
        yes: "yes"
    videoSettings:
      label: Video Settings
      type: headline
    stream:
      label: Video external stream link (.M3U8)
      type: url
    mp4:
      label: Video external file link (.MP4)
      type: url
    mp4:
      label: Video external file link (.WEBM)
      type: url
    filemp4:
      label: Video File (.MP4)
      type: select
      options: videos
    filewebm:
      label: Video File (.WEBM)
      type: select
      options: videos
fields:
  prevnext: prevnext
  tab1:
    label: General
    type: tabs
  title:
    label: Title
    type: title
    width: 1/2
  date:
    label: Year
    type: date
    format: YYYY
    default: today
    required: true
    width: 1/4
  featured:
    label: Featured image
    type: image
    width: 1/4
  format:
    label: Format
    type: text
    width: 1/2
  materials:
    label: Materials
    type: text
    width: 1/2
  text:
    label: Description
    type: textarea
  medias:
    label: Images
    type: Images
  tab2:
    label: Texts
    type: tabs
  textFr :
    label: Français
    type: textarea
  textEn :
    label: English
    type: textarea


