title: Project
pages: false
files:
  sortable: true
  max: null
  hide: false
  sanitize: true
  fields: null
  size: null
  width: null
  height: null
  fields:
    caption:
      label: Caption
      type: textarea
    notinintro:
      label: Remove from intro
      type: toggle
      default: no
      options:
        no: "no"
        yes: "yes"
fields:
  prevnext: prevnext
  title:
    label: Title
    type: title
    width: 3/4
  featured:
    label: Featured image
    type: image
    width: 1/4
  sound:
    label: Audio
    type: select
    options: audio
    width: 3/4
  inIntro:
    label: Add to intro
    type: toggle
    width: 1/4
    columns: 1
  content:
    label: Text
    type: textarea
  text:
    label: Description
    type: textarea
  medias:
    label: Images
    type: Images



