title: Project
pages: false
files:
  sortable: true
  max: null
  hide: false
  sanitize: true
  fields: null
  size: null
  width: null
  height: null
  fields:
    caption:
      label: Caption
      type: textarea
    notingrid:
      label: Remove from grid
      type: toggle
      default: no
      options:
        no: "no"
        yes: "yes"
fields:
  prevnext: prevnext
  tab1:
    label: General
    type: tabs
  title:
    label: Title
    type: title
    width: 1/2
  date:
    label: Year
    type: date
    format: YYYY
    width: 1/4
  featured:
    label: Featured image
    type: image
    width: 1/4
  format:
    label: Format
    type: text
    width: 1/2
  materials:
    label: Materials
    type: text
    width: 1/2
  text:
    label: Description
    type: textarea
  medias:
    label: Images
    type: Images
  tab2:
    label: Texts
    type: tabs
  textFr :
    label: Français
    type: textarea
  textEn :
    label: English
    type: textarea


