title: Project
pages: false
files:
  sortable: true
  max: null
  hide: false
  sanitize: true
  fields: null
  size: null
  width: null
  height: null
  fields:
    caption:
      label: Caption
      type: textarea
    notinintro:
      label: Remove from intro
      type: toggle
      default: no
      options:
        no: "no"
        yes: "yes"
fields:
  prevnext: prevnext
  tab1:
    label: General
    type: tabs
  title:
    label: Title
    type: title
    width: 3/4
  featured:
    label: Featured image
    type: image
    width: 1/4
  medias:
    label: Images
    type: Images
  tab2:
    label: Infos
    type: tabs
  format:
    label: Format
    type: text
    width: 3/4
  date:
    label: Year
    type: date
    format: YYYY
    width: 1/4
  text:
    label: Description
    type: textarea


